# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d94bc527eb349bca65ef4cc5cf5ada8c28f05f68bc842a196230c169a4e59c00311d6d8ef35a5306599bbf62ff1dcc378c0c134003507ceebd2ba2057bb1881

test:
  secret_key_base: baedac17699e7d0033fd5edba102ac291ab328e4c52de0d8e3dd5a70e30757ab9fd6c09732ff8b840d95fd75252a7186696a500f760008615dd2ea8b9817bd59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
